version = 1
name = "dual-custody-enclave"
uuid = "enclave_d33eb16e9dd7"
app_uuid = "app_80eeb9f27e5b"
team_uuid = "eefa0c67dcb9"
debug = false
dockerfile = "./Dockerfile"
api_key_auth = false
trx_logging = true
tls_termination = true
forward_proxy_protocol = false
trusted_headers = []

[egress]
enabled = true
destinations = ["sepolia.infura.io", "dual-custody-backend.davidnugent2425.repl.co"]

[scaling]
desired_replicas = 1

[signing]
certPath = "./cert.pem"
keyPath = "./key.pem"
